import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import {
  Apple,
  Activity,
  Droplets,
  HeartPulse,
  Moon,
  ShieldAlert,
  Sparkles,
  Stethoscope,
} from "lucide-react";

export const Route = createFileRoute("/insights")({
  head: () => ({
    meta: [
      { title: "AI Insights — NeuroDiab" },
      { name: "description", content: "Personalized AI-generated medical recommendations." },
    ],
  }),
  component: InsightsPage,
});

const recommendations = [
  {
    icon: Apple,
    title: "Low-glycemic nutrition",
    body: "Prioritize leafy greens, legumes and whole grains. Limit refined carbs to stabilize glucose response.",
    risk: "Moderate",
  },
  {
    icon: Activity,
    title: "150 min weekly activity",
    body: "Mix moderate aerobic with resistance training — improves insulin sensitivity within 4–6 weeks.",
    risk: "Low",
  },
  {
    icon: Droplets,
    title: "Hydration & HbA1c check",
    body: "Hydrate ≥ 2L/day. Schedule a quarterly HbA1c lab to track long-term glycemic control.",
    risk: "Low",
  },
  {
    icon: Moon,
    title: "Sleep regulation",
    body: "Aim for 7–9h. Poor sleep correlates with a 28% rise in fasting glucose variability.",
    risk: "Moderate",
  },
  {
    icon: Stethoscope,
    title: "Clinical follow-up",
    body: "If risk > 50%, consult an endocrinologist within 30 days for confirmatory diagnostics.",
    risk: "High",
  },
  {
    icon: HeartPulse,
    title: "Cardiometabolic monitor",
    body: "Track blood pressure weekly. Hypertension significantly amplifies diabetic complications.",
    risk: "Moderate",
  },
];

const riskStyles: Record<string, string> = {
  Low: "bg-[color:var(--success)]/15 text-[color:var(--success)]",
  Moderate: "bg-[color:var(--warning)]/15 text-[color:var(--warning)]",
  High: "bg-destructive/15 text-destructive",
};

function InsightsPage() {
  return (
    <div className="space-y-6">
      <header className="flex items-end justify-between gap-4 flex-wrap">
        <div>
          <h1 className="font-[Space_Grotesk] text-3xl md:text-4xl font-bold tracking-tight">
            AI Insights
          </h1>
          <p className="text-muted-foreground mt-1 text-sm">
            Personalized recommendations generated by the NeuroDiab clinical reasoning engine.
          </p>
        </div>
        <div className="glass px-4 py-2 rounded-xl text-xs flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-primary" />
          Updated just now
        </div>
      </header>

      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-strong rounded-3xl p-6 md:p-8 relative overflow-hidden"
      >
        <div className="absolute -top-20 -right-20 w-72 h-72 rounded-full gradient-aurora-bg animate-aurora blur-3xl opacity-30" />
        <div className="relative flex items-start gap-4">
          <div className="w-12 h-12 rounded-2xl gradient-primary-bg flex items-center justify-center shadow-glow animate-pulse-glow shrink-0">
            <ShieldAlert className="w-6 h-6 text-primary-foreground" />
          </div>
          <div>
            <h2 className="font-semibold text-lg">Overall risk level: Moderate</h2>
            <p className="text-sm text-muted-foreground mt-1 max-w-2xl">
              Based on the most recent prediction, the patient is in a watch-and-act zone.
              Adopting the following interventions can meaningfully reduce conversion risk
              over the next 12 months.
            </p>
          </div>
        </div>
      </motion.div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {recommendations.map((r, i) => (
          <motion.div
            key={r.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.06 }}
            whileHover={{ y: -4 }}
            className="glass rounded-2xl p-5 hover:glow-ring transition-all"
          >
            <div className="flex items-start justify-between mb-3">
              <div className="w-11 h-11 rounded-xl gradient-primary-bg flex items-center justify-center shadow-glow">
                <r.icon className="w-5 h-5 text-primary-foreground" />
              </div>
              <span className={`text-[10px] uppercase tracking-widest font-semibold px-2 py-1 rounded-full ${riskStyles[r.risk]}`}>
                {r.risk}
              </span>
            </div>
            <h3 className="font-semibold mb-1">{r.title}</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">{r.body}</p>
          </motion.div>
        ))}
      </div>
    </div>
  );
}